### ISSUE TITLE
Unable to upload replay that was previously uploaded from an account marked for deletion

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#462] opened 2023-09-16 15:40 UTC
To reproduce:
1. Upload a replay from an account
2. Delete the account (Mark it for deletion)
3. Upload the replay from another account

You will get am error message like
"This replay already exists. /replays/th11/321943"
However, trying to access the replay gives a 404

**Comment by jgdhs27** [comment] 2023-09-16 15:56
The cause seems to be that the account is not actually deleted immediately, and therefore the replay remains in the database. After running `manage.py delete_old_data`, I was able to upload the replay as expected.

**Comment by jgdhs27** [comment] 2023-09-16 16:12
I looked inside the DB and the Replay & ReplayFile objects still exist. [We 404 on inaccessible replays](https://github.com/n-rook/thscoreboard/blob/main/project/thscoreboard/replays/views/view_replay.py#L249).

**Comment by n-rook** [comment] 2023-09-16 19:47
There are a few bugs here, I think. Replays assigned to deleted users are not immediately erased. This is by design, so if the user changes their mind they can recover their replay. However, it does not seem right that a replay attached to a deleted user would prevent another user from uploading the same replay.

I think there are two bugs here:
* A replay attached to a deleted user is in a sort of half-life, where it will come back to life if the user in question decides to reopen their account. However, this should not prevent a new user from uploading the same replay. (Chances are the "new user" is the same person with a new account, as it was in this case.) This is the main bug.
* A replay attached to a deleted user should not be displayed on the front page or anywhere else. I just filed #463 for this.

And a UI problem (that isn't really a bug):
* We should be more explicit about which replay is blocking a newly uploaded replay. That would not have helped much here but it would help in other cases.

There are really two ways to fix the first issue. When we create a replay, we could delete matching replays attached to the same user. Or, we could make the constraint on replay files only apply to replays that are attached to active users.

I lean toward the first option— I can't think of a good way to do the second option without denormalizing the database.

**Closed** 2023-10-06 16:39 UTC
Labels: bug
